//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysForVolunteer
    {
        public long DaysForVolunteerId { get; set; }
        public long DayofWeek { get; set; }
        public System.TimeSpan HourStart { get; set; }
        public System.TimeSpan HourEnd { get; set; }
        public long RangeHours { get; set; }
        public long TypesOfTimesId { get; set; }
        public long VolunteerId { get; set; }
    
        public virtual TypesOfTime TypesOfTime { get; set; }
        public virtual User User { get; set; }
    }
}
