//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HandToHanddEntities : DbContext
    {
        public HandToHanddEntities()
            : base("name=HandToHanddEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockedUser> BlockedUsers { get; set; }
        public virtual DbSet<HelpRequest> HelpRequests { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<RequestsForVolunteer> RequestsForVolunteers { get; set; }
        public virtual DbSet<TypeOfVolunteering> TypeOfVolunteerings { get; set; }
        public virtual DbSet<TypesOfTime> TypesOfTimes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VolunteeringForUser> VolunteeringForUsers { get; set; }
        public virtual DbSet<DaysForVolunteer> DaysForVolunteers { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
    }
}
