//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HelpRequest()
        {
            this.RequestsForVolunteers = new HashSet<RequestsForVolunteer>();
        }
    
        public long HelpRequestId { get; set; }
        public long RequesterId { get; set; }
        public long TypeOfVolunteerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StartHour { get; set; }
        public System.TimeSpan EndHour { get; set; }
    
        public virtual User User { get; set; }
        public virtual TypeOfVolunteering TypeOfVolunteering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsForVolunteer> RequestsForVolunteers { get; set; }
    }
}
