//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.HelpRequests = new HashSet<HelpRequest>();
            this.RequestsForVolunteers = new HashSet<RequestsForVolunteer>();
            this.VolunteeringForUsers = new HashSet<VolunteeringForUser>();
            this.DaysForVolunteers = new HashSet<DaysForVolunteer>();
        }
    
        public long UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public long UserPhone { get; set; }
        public string UserPassword { get; set; }
        public string UserMail { get; set; }
        public string UserAdress { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual BlockedUser BlockedUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpRequest> HelpRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsForVolunteer> RequestsForVolunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteeringForUser> VolunteeringForUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysForVolunteer> DaysForVolunteers { get; set; }
        public virtual Area Area { get; set; }
    }
}
