//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteeringForUser
    {
        public long VolunteeringForUsersId { get; set; }
        public long TypeOfVolunteerId { get; set; }
        public long UserId { get; set; }
    
        public virtual TypeOfVolunteering TypeOfVolunteering { get; set; }
        public virtual User User { get; set; }
    }
}
